# Generated by Django 4.1.4 on 2022-12-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('province', models.CharField(max_length=20)),
                ('districts', models.CharField(max_length=20)),
                ('wards', models.CharField(max_length=20)),
                ('specific_address', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=11)),
                ('customer_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Chờ xác nhận'), (1, 'Đang giao'), (2, 'Đã giao')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('price_discount', models.FloatField(default=0)),
                ('discount', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Ẩn'), (1, 'Công khai')], default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TimeFrameReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_product', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=10)),
                ('product_size', models.CharField(max_length=20)),
                ('product_price', models.FloatField()),
                ('product_discount', models.BooleanField(default=False)),
                ('product_price_discount', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes_product', to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='core.productcategory'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_detail', to='core.order')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_detail', to='core.productattribute')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='time_frame_receive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeframereceive'),
        ),
    ]
