# Generated by Django 4.1.4 on 2022-12-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_productattribute_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_size', to='core.productsize'),
        ),
    ]
