# Generated by Django 4.1.4 on 2022-12-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_amount_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='/sadas', upload_to=''),
            preserve_default=False,
        ),
    ]
